### ISSUE TITLE
Change if Statement

### ISSUE THREAD

**Issue by raphaelschnick** [T0myyde/GuardianSystemByteFox#2]
https://github.com/T0myyde/GuardianSystemByteFox/blob/bef363c55cda2192064e5bcd9ef3e3504a2c13c7/src/main/java/ch/tom/bytefox/guardiansystembytefox/commands/ReportCommand.java#L22

Use here `.length == 2` and remove else block

**Comment by Nxile7** [comment]
This is not the current version, this was only valid as an intermediate memory. thank you
